### ISSUE TITLE
Return errors and not working because missing static variables.

### ISSUE THREAD

**Issue by Mandallaz** [datacorner/les-tutos-datacorner.fr#2]
# Corrected version (Google Colab)

def getPage(url):
    page = requests.get(url)
    doc = lh.fromstring(page.content)
    cols = ['nomJeux','desc','sortie','test','avis']
    tags =['//a[@class="gameTitleLink__196nPy"]',
           '//p[@class="description__1-Pqha"]',
           '//span[@class="releaseDate__1RvUmc"]',
           '//span[@class="editorialRating__1tYu_r"]',
           '//span[@class="userRating__1y96su"]']
    # Get the Web data via XPath
    content = []
    for i in range(len(tags)):
        content.append(doc.xpath(tags[i]))
 
    # Gather the data into a Pandas DataFrame array
    df_liste = []
    for j in range(len(tags)):
        tmp = pd.DataFrame([content[j][i].text_content().strip() for i in range(len(content[i]))], columns=[cols[j]])
        tmp['key'] = tmp.index
        df_liste.append(tmp)
 
    # Build the unique Dataframe with one tag (xpath) content per column
    liste = df_liste[0]
    for j in range(len(tags)-1):
        liste = liste.join(df_liste[j+1], on='key', how='left', lsuffix='_l', rsuffix='_r')
        liste['key'] = liste.index
        del liste['key_l']
        del liste['key_r']
 
    return liste

%load_ext google.colab.data_table
import requests
import lxml.html as lh
import pandas as pd

getPage('http://www.jeuxvideo.com/meilleurs/').head()

def getPages(_nbPages, _url):
    liste_finale = pd.DataFrame()
    for i in range (_nbPages):
        liste = getPage(_url + '?p=' + str(i+1))
        liste_finale = pd.concat([liste_finale, liste], ignore_index=True)
    return liste_finale

import requests
import lxml.html as lh
import pandas as pd

liste_totale = getPages(50, 'http://www.jeuxvideo.com/meilleurs/')

# Allow sorting by rating
liste_totale["test"] = liste_totale["test"].str.split("/", n = 1, expand = True)
liste_totale["avis"] = liste_totale["avis"].str.split("/", n = 1, expand = True)
liste_totale["test"] = liste_totale["test"].astype(float)
liste_totale["avis"] = liste_totale["avis"].astype(float)

%load_ext google.colab.data_table
liste_totale

**Comment by datacorner** [comment]
Hi,
I've just re-test the code successfully and that works on colab (also). 
So can you specify the notebook, the error, etc. please ?
Thanks
